def        NEXUS_VERSION = "nexus3"
def        NEXUS_PROTOCOL = "http"
def        NEXUS_URL = "172.17.0.1:10680" 
def        NEXUS_REPOSITORY = "maven-snapshots"
def        NEXUS_CREDENTIAL_ID = "nexus-password"